// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB49DkFEsRI5QTncGI8tcG_domUgF_sQuw',
    appId: '1:555964003017:web:fcbf1e55eaaa6319bf9318',
    messagingSenderId: '555964003017',
    projectId: 'chattingapp-flutter',
    authDomain: 'chattingapp-flutter.firebaseapp.com',
    databaseURL: 'https://chattingapp-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'chattingapp-flutter.appspot.com',
    measurementId: 'G-EH156DX2ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQ0VptTslVn6UlC8fNh7yDYeax8oWw5M',
    appId: '1:555964003017:android:0bdbdabe8dae663cbf9318',
    messagingSenderId: '555964003017',
    projectId: 'chattingapp-flutter',
    databaseURL: 'https://chattingapp-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'chattingapp-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCyWV1qp850hdiT9XoxWQB6MpWVceMnR8',
    appId: '1:555964003017:ios:93cecd93c9765e28bf9318',
    messagingSenderId: '555964003017',
    projectId: 'chattingapp-flutter',
    databaseURL: 'https://chattingapp-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'chattingapp-flutter.appspot.com',
    iosClientId: '555964003017-bqi5sp037e85e15mqfevpcrrbdk4pvlv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCyWV1qp850hdiT9XoxWQB6MpWVceMnR8',
    appId: '1:555964003017:ios:4bd7637b7e1549efbf9318',
    messagingSenderId: '555964003017',
    projectId: 'chattingapp-flutter',
    databaseURL: 'https://chattingapp-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'chattingapp-flutter.appspot.com',
    iosClientId: '555964003017-8etadpkjgqvii564gasdi704mqlikacr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChattingApp.RunnerTests',
  );
}
